kabaadiwala/addkabaad/urls.py
from django.urls	import	path
from . import	views
app_name =	'addkabaad'
urlpatterns	=	[
	path('create-sell/',	views.product_create,kwargs={'decision': 'sell'},	name='create-sell'),
	path('create-donate/',	views.product_create,kwargs={'decision': 'donate'},	name='create-donate'),
	path('detail/<int:id>/<slug:slug>/',views.product_detail, name='detail'),
	path('',views.product_list,	name='list'),
    path('<slug:category_slug>/', views.product_list,
    name='product_list_by_category'),

]

kabaadiwala/home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name =	'home'
urlpatterns=[
    path('',views.index,name='index')
  
    

]

kabaadiwala/kabaadiwala/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('account/',include('account.urls')),
    path('',include('account.urls')),
    path('kabaad/',	include('addkabaad.urls',	namespace='kabaad')),
    path('cart/',include('shopping_cart.urls',namespace='cart')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

kabaadiwala/shopping_cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    processOrder,
   
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'process_order/',processOrder, name='process_order'),
    
]

kabaadiwala/shopping_cart/models.py
from __future__ import unicode_literals
from django.db import models
from account.models import Profile
from addkabaad.models import Product


class OrderItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)


class ShippingAddress(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    address = models.CharField(max_length=200,null=True)
    city = models.CharField(max_length=200,null=True)
    state = models.CharField(max_length=200,null=True)
    zipcode = models.CharField(max_length=200,null=True)
    date_added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.address

kabaadiwala/shopping_cart/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import OrderItem,Order,ShippingAddress
from account.models import Profile
from addkabaad.models import Product
import datetime
import json
from django.views.decorators.csrf import csrf_exempt



def get_user_pending_order(request):
    # get order for the correct user
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0


@login_required()
def add_to_cart(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # filter products by id
    product = Product.objects.filter(id=kwargs.get('item_id', "")).first()
    # check if the user already owns this product
    if product in request.user.profile.products.all():
        messages.info(request, 'You already own this ebook')
        return redirect(reverse('addkabaad:list')) 
    # create orderItem of the selected product
    order_item, status = OrderItem.objects.get_or_create(product=product)
    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
    
        user_order.save()

    # show confirmation message and redirect back to the same page
    messages.info(request, "item added to cart")
    return redirect(reverse('addkabaad:list'))


@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('shopping_cart:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'order_summary.html', context)

@login_required()
def checkout(request):  
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order,
    }

    return render(request, 'checkout.html', context)

@csrf_exempt
@login_required
def processOrder(request):
    if request.method=='POST':
        data=json.loads(request.body)
        user_profile = get_object_or_404(Profile, user=request.user)
        user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
        total=data['form']['total']
        if str(total)==str(user_order.get_cart_total()):
            order_items=user_order.items.all()
            for item in order_items:
                product=item.product
                product.available=False
                product.save()
            user_order.is_ordered=True
        user_order.save()
        ShippingAddress.objects.create(
            owner=user_profile,
            order=user_order,
            is_ordered = True,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
            )
        return JsonResponse('Order placed',safe=False)

kabaadiwala/shopping_cart/templates/checkout.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container">
<div class="row mt-5">
  <div class="col-lg-6 mt-5">
    <div class="box-element" id="form-wrapper">
      <form id="form">
        <div id="shipping-info">
        <hr>
        <h2>shipping Information</h2>
        <hr>
        <div class="form-field">
          <input class="form-control" type="text" name="address" placeholder="Address...">
        </div>
        <div class="form-field">
          <input class="form-control" type="text" name="city" placeholder="City...">
        </div>
        <div class="form-field">
          <input class="form-control" type="text" name="state" placeholder="State...">
        </div>
        <div class="form-field">
          <input class="form-control" type="text" name="zipcode" placeholder="Zip code...">
        </div>
        </div>
        <hr>
      
      </form>
    <div>
      <div class="box-element mb-5" id="payment-info">
        <small></small>
        <button class="btn btn-success" type="button" id="placeOrder">place Order</button>
        
      </div>
  </div>
</div>
  </div>
  <div class="col-lg-6 mt-5">
    <div class="box-element">
      
      <hr>
      <h3>Order Summary</h3>
      <hr>
      {% for item in order.get_cart_items %}
      <div class="cart-row">
        <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
        <div style="flex:2"><p>{{item.product.name}}</p></div>
        <div style="flex:2"><p>{{item.product.price}}</p></div>
   
      </div>
      {% endfor %}
    </div>
  
  </div>
 </div>
</div>

<script>
  var form=document.getElementById('form')
  var total='{{order.get_cart_total|floatformat:2}}'
  document.getElementById('placeOrder').addEventListener('click',function(e){
    submitFormData()
  })

  function submitFormData(){
    console.log("hey order placed")
   
    var userFormData={
      'name':null,
      'email':null,
      'total':total,
    }

    
    var shippingInfo={
      'address':form.address.value,
      'city':form.city.value,
      'state':form.state.value,
      'zipcode':form.zipcode.value,
    }
  
  fetch('/cart/process_order/',{
    method:'POST',
    headers:{
      'Content-Type': 'application/json',
      
    },
    body: JSON.stringify({'form':userFormData,'shipping':shippingInfo})})
  .then(response => response.json())
  .then(data =>{
    console.log("success",data);
    alert('order placed successfully');
  
    window.location.href="{% url 'home:index' %}"
    
  })
  
  }
  
</script>


{% endblock %}

kabaadiwala/shopping_cart/templates/order_summary.html
{% extends "base.html" %}

{% block content %}

 <section>
  <div class="container">
   <div class="row">
    <table class="table table-hover table-bordered text-center mt-5">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.product.name }}
            <span class="pull-right">
              <a href="{% url 'shopping_cart:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a>
            </span>
          </td>
          <td>{{ item.product.price }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong class="pull-right">Order Total:</strong>
        </td>
        
        <td colspan= 1>
          ₹<strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'addkabaad:list' %}" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
        <td colspan=2>
          {% if order.get_cart_items %}
            <a href="{% url 'shopping_cart:checkout' %}" class="pull-right btn btn-primary">Checkout</a>
          {% endif %}
        </td>
      </tr>
    </table>
     
   </div>
   </div>
 </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}

kabaadiwala/shopping_cart/templates/purchase_success.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thank you for your purchase!</h1>
    <a href="{% url 'products:product-list' %}">Head back home</a>
{% endblock content %}

kabaadiwala/shopping_cart/templates/stripe_default_form.html
script src="https://js.stripe.com/v3/"></script>

<form action="." method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="{{ STRIPE_PUBLISHABLE_KEY }}"
    data-amount="999"
    data-name="Justdjango"
    data-description="Example charge"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto">
  </script>
</form>