kabaadiwala/addkabaad/urls.py
from django.urls	import	path
from . import	views
app_name =	'addkabaad'
urlpatterns	=	[
	path('create-sell/',	views.product_create,kwargs={'decision': 'sell'},	name='create-sell'),
	path('create-donate/',	views.product_create,kwargs={'decision': 'donate'},	name='create-donate'),
	path('detail/<int:id>/<slug:slug>/',views.product_detail, name='detail'),
	path('',views.product_list,	name='list'),
    path('<slug:category_slug>/', views.product_list,
    name='product_list_by_category'),

]

kabaadiwala/home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name =	'home'
urlpatterns=[
    path('',views.index,name='index')
  
    

]

kabaadiwala/kabaadiwala/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('account/',include('account.urls')),
    path('',include('account.urls')),
    path('kabaad/',	include('addkabaad.urls',	namespace='kabaad')),
    path('cart/',include('shopping_cart.urls',namespace='cart')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

kabaadiwala/shopping_cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    processOrder,
   
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'process_order/',processOrder, name='process_order'),
    
]

kabaadiwala/addkabaad/models.py
from django.db	import	models
from django.conf import	settings
from django.utils.text	import	slugify
from django.urls import	reverse

class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def	save(self,*args,**kwargs):
        if	not	self.slug:
            self.slug=slugify(self.name)
        super(Category,self).save(*args,**kwargs)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('kabaad:product_list_by_category',args=[self.slug])



class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
    related_name='product_created',on_delete=models.CASCADE)
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='product/')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    decision = models.BooleanField(default=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    def __str__(self):
        return self.name
    def	save(self,*args,**kwargs):
        if	not	self.slug:
            self.slug=slugify(self.name)
        super(Product,self).save(*args,**kwargs)
    def	get_absolute_url(self):
        return	reverse('addkabaad:detail',args=[self.id,self.slug])
    

  
    
    

kabaadiwala/addkabaad/forms.py
from	django	import	forms
from	.models	import	Product
from	urllib	import	request
from	django.core.files.base	import	ContentFile
from	django.utils.text	import slugify

class	ProductCreateForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=('name','category','image','description','price')
        
  
    
   
   
    
    

kabaadiwala/addkabaad/views.py
from django.shortcuts import render, redirect
from .forms	import	ProductCreateForm
from django.contrib	import	messages
from django.contrib.auth.decorators	import login_required
from django.shortcuts import get_object_or_404
from .models import	Product,Category
from django.core.paginator	import	Paginator,	EmptyPage,	\
	PageNotAnInteger
from django.http	import	HttpResponse
from shopping_cart.models import Order
# Create your views here.

@login_required
def	product_create(request,**kwargs):
    
    if	request.method	==	'POST':
	#	form	is	sent
        form = ProductCreateForm(request.POST,request.FILES)
        if form.is_valid():
            #form data is valid
            cd=form.cleaned_data
            print("hey",cd)
            new_item=form.save(commit=False)
            #assign	current	user to	the	item
            new_item.user = request.user
            typo = kwargs.get('decision', "")
            if typo=="sell":
                new_item.decision=False
            else:
                new_item.decision=True
            new_item.save()
           
            
            messages.success(request,	'Product	added	successfully')
            # redirect	to	new	created	item	detail	view
            return redirect(new_item.get_absolute_url())
        print("hh")
    else:
	# build	form	with	data	provided	by	the	bookmarklet	via	GET
        form = ProductCreateForm(data=request.GET)
    return render(request,
    'products/product/create.html',
    {'section':	'products',
    'form':	form})

@login_required
def	product_detail(request,id,slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    object_list = Product.objects.all()
    filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
    current_order_products = []
    print(filtered_orders)
    if filtered_orders.exists():
        print("heuu")
        user_order = filtered_orders[0]
        user_order_items = user_order.items.all()
        current_order_products = [product.product for product in user_order_items]
    context = {
        'object_list': object_list,
        'current_order_products': current_order_products,
        'section':'products',
        'product': product
    }
   
    return render(request,'products/product/detail.html',context)

@login_required
def	product_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products=Product.objects.all()
    products = products.filter(decision=False)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category,decision=False)
    paginator = Paginator(products,	8)
    page = request.GET.get('page')
    try:
        products	=	paginator.page(page)
    except	PageNotAnInteger:
        products	=	paginator.page(1)
    except	EmptyPage:
        if	request.is_ajax():
	        return	HttpResponse('')
        products=paginator.page(paginator.num_pages)
    if request.is_ajax():
            return	render(request,'products/product/list_ajax.html',{'category': category,'categories': categories,'section':'products','products': products})
    return	render(request,'products/product/list.html',{'category': category,'categories': categories,'section':'products','products': products})

kabaadiwala/addkabaad/templates/products/product/create.html
{%	extends	"base.html"	%}
{%	block	title	%}Add our kabaad{%	endblock	%}
{%	block	content	%}
    <div class="section about ">
        <div class="container">
            <div class="row">
               <div class="col-12">
                  <div class="titlepage">
                 <h2><strong class="black">Product</strong> Details</h2>
                <span></span>
             </div>
           </div>
        </div>
    </div>
 </div>
 <table style="background-color:#1E90FF; " align="center"  cellspacing=2px cellpadding=2px id="form" >
	<form	action="."	method="post" enctype="multipart/form-data">
        {%	csrf_token	%}
        {{	form.as_table	}}
        
        </table>
        <table align="center" cellspacing=20px cellpadding=20px width="10%">
        <tr>
        <td> <input	type="submit"	value="Submit"></td>
        
        <td><input type="reset" value="RESET"></input></td>
    </form>    
    </tr>
        </table>
{%	endblock	%}

kabaadiwala/addkabaad/templates/products/product/detail.html
{%	extends	"base.html"	%}

{%	block	title	%}{{	product.name	}}{%	endblock	%}

{%	block	content	%}

<br><br><br>

<!--Section: Block Content-->
<section class="mb-5">
<div class="container">
    <div class="row">
      <div class="col-md-4 mb-4 mb-md-0">
        <div id="mdb-lightbox-ui"></div>
        <div class="mdb-lightbox">
        <div class="row product-gallery mx-1">
            <div class="col-12 mb-0">
              <figure class="view overlay rounded z-depth-1 main-img">
                <img src="{% if product.image %} {{ product.image.url }}  {% endif %}" 
                    class="detail-img">
              </figure>
            </div>
        </div>
        </div>
        </div>
      <div class="col-md-8 ">
            <div class="product-detail-text">
                <h2>{{product.name}}</h2>
                <p class="mb-2 text-muted text-uppercase small">{{product.category}}</p>
                <p><span class="mr-1"><strong>₹{{product.price}}</strong></span></p>
                <p class="pt-1">{{product.description}}</p>
                
                {% if user == product.user %}
                    <h3>You own this</h3>
                {% elif product in current_order_products %}
                <a href="{% url 'cart:order_summary'%}" class="btn btn-warning">Go to Cart</a>
                {% else %}
                <p>Availability:{{product.available}}</p>
                <a href="{% url 'cart:add_to_cart' product.id %}" class="btn btn-warning">Add to Cart</a>
                {% endif %}
            </div>
      </div>
    </div>
   </div>
  </section>
  <!--Section: Block Content-->
<script>
    $(document).ready(function () {
    // MDB Lightbox Init
    $(function () {
    $("#mdb-lightbox-ui").load("mdb-addons/mdb-lightbox-ui.html");
    });
    });
</script>

    
{%	endblock	%}  

kabaadiwala/addkabaad/templates/products/product/list.html
{% extends "base.html" %}
{% load static %}
{% block	title	%}Product available{%	endblock	%}
{% block content	%}


 <div id="category" class="section  product">
    <div class="container">
       <div class="row">
          <div class="col-md-12 ">
             <div class="titlepage">
                <h2><strong class="black"> Cate</strong>gories</h2>
                {% if not category %}
                <span class="badge badge-primary"><a href="{% url "kabaad:list" %}">All</a></span>
                {% else %}
                <span class="badge badge-dark"><a href="{% url "kabaad:list" %}">All</a></span>
                {% endif %}
                {% for c in categories %}
                  {% if category.slug == c.slug %}<span class="badge badge-primary"><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></span>
                  {% else %}
                    <span class="badge badge-dark"><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></span>
                    {% endif %}
                    {% endfor %}
              
               </div>
                    <div id="main" class="product-list">
                    <h1>{% if category %}{{ category.name }}{% else %}Products
                    {% endif %}</h1>
             </div>
          </div>
       </div>
    </div>
 </div>



 <div class="clothes_main section ">
    <div class="container">
      <div class="row">
         
        {% for product in products %}
        <!-- if product user is current user the he wont see his product to uy-->
        {% if user != product.user %}
        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
           <div class="sport_product">
                <figure><a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %} {{ product.image.url }}
                    {%else %}{% static "img/driving_licence.jpg" %}{% endif %}" width='250' height='300'>
                    </a></figure>

                    
              <h3> ₹<strong class="price_text"> {{ product.price }}</strong></h3>
               <h4><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
            </div>
         </div>
         {% endif %}
         {% endfor %}
         </div>
       </div>
      </div>
    
        
        
       
      
      
        
       
      


{%	endblock	%}