kabaadiwala/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns=[
    #path('login/',views.user_login,name='login')
    path('login/',	auth_views.LoginView.as_view(),	name='login'),
	path('logout/',	auth_views.LogoutView.as_view(),	name='logout'),
    path('',	views.dashboard,	name='dashboard'),
    #	change	password	urls
    path('password_change/',
        auth_views.PasswordChangeView.as_view(),	
                name='password_change'),
    path('password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(),	
        name='password_change_done'),

    #	reset	password	urls
    path('password_reset/',
        auth_views.PasswordResetView.as_view(),
                name='password_reset'),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
                name='password_reset_confirm'),
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    path('register/',	views.register,	name='register'),
    path('edit/',	views.edit,	name='edit'),

    #path('users/follow/',	views.user_follow,	name='user_follow'),

    #path('users/',	views.user_list,	name='user_list'),
	#path('users/<username>/',views.user_detail,	name='user_detail'),
    

]

kabaadiwala/addkabaad/urls.py
from django.urls	import	path
from . import	views
app_name =	'addkabaad'
urlpatterns	=	[
	path('create-sell/',	views.product_create,kwargs={'decision': 'sell'},	name='create-sell'),
	path('create-donate/',	views.product_create,kwargs={'decision': 'donate'},	name='create-donate'),
	path('detail/<int:id>/<slug:slug>/',views.product_detail, name='detail'),
	path('',views.product_list,	name='list'),
    path('<slug:category_slug>/', views.product_list,
    name='product_list_by_category'),

]

kabaadiwala/home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name =	'home'
urlpatterns=[
    path('',views.index,name='index')
  
    

]

kabaadiwala/kabaadiwala/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('account/',include('account.urls')),
    path('',include('account.urls')),
    path('kabaad/',	include('addkabaad.urls',	namespace='kabaad')),
    path('cart/',include('shopping_cart.urls',namespace='cart')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

kabaadiwala/account/models.py
from	django.db	import	models
from	django.conf	import	settings
from	django.contrib.auth.models	import	User
from addkabaad.models import Product
from django.db.models.signals import post_save



class	Profile(models.Model):
	user=models.OneToOneField(settings.AUTH_USER_MODEL,
			on_delete=models.CASCADE)
	date_of_birth =	models.DateField(blank=True,	null=True)
	photo	=	models.ImageField(upload_to='users/%Y/%m/%d/',
	blank=True)
	products=models.ManyToManyField(Product,blank=True)
	def	__str__(self):
	    return	'Profile	for	user	{}'.format(self.user.username)
#def post_save_profile_create(sender, instance, created, *args, **kwargs):
   		#user_profile, created = Profile.objects.get_or_create(user=instance)




#post_save.connect(post_save_profile_create, sender=settings.AUTH_USER_MODEL)

kabaadiwala/account/forms.py
from django import forms
from	django.contrib.auth.models	import	User

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)


class	UserRegistrationForm(forms.ModelForm):
    password	=	forms.CharField(label='Password',
            widget=forms.PasswordInput)
    password2	=	forms.CharField(label='Repeat	password',
    widget=forms.PasswordInput)
    class Meta:
        model = User
        fields	=	('username','first_name','email')
    def	clean_password2(self):
        cd	=	self.cleaned_data
        if	cd['password']	!=	cd['password2']:
                raise	forms.ValidationError('Passwords	don\'t	match.')
        return	cd['password2']

from	.models	import	Profile
class	UserEditForm(forms.ModelForm):
    class	Meta:
        model=User
        fields	=	('first_name',	'last_name',	'email')
class	ProfileEditForm(forms.ModelForm):
    class	Meta:
        model	=	Profile
        fields	=	('date_of_birth',	'photo')

kabaadiwala/account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate,login
from .forms import LoginForm,UserRegistrationForm,UserEditForm,	ProfileEditForm
from django.contrib.auth.decorators	import	login_required
from .models	import	Profile
from django.contrib	import	messages
from	django.shortcuts	import	get_object_or_404
from	django.contrib.auth.models	import	User
from	django.http	import	JsonResponse
from	django.views.decorators.http	import	require_POST
#from	common.decorators	import	ajax_required

#from	actions.utils	import	create_action
#from	actions.models	import	Action
# Create your views here.

@login_required
def	dashboard(request):
	# Display all actions by default
    return	render(request,
	'account/dashboard.html',
	{'section':'dashboard'})

def	register(request):
    if	request.method	==	'POST':
        user_form=UserRegistrationForm(request.POST)
        if	user_form.is_valid():
                #	Create	a	new	user	object	but	avoid	saving	it	yet
                new_user	=	user_form.save(commit=False)
                #	Set	the	chosen	password
                new_user.set_password(
                        user_form.cleaned_data['password'])
                #	Save	the	User	object
         
         
         
                new_user.save()
                Profile.objects.create(user=new_user)
                return	render(request,
                'account/register_done.html',
                {'new_user':	new_user})
    else:
        user_form=UserRegistrationForm()
    return	render(request,
	'account/register.html',
	{'user_form':	user_form})


@login_required
def	edit(request):
    if	request.method	==	'POST':
        user_form=UserEditForm(instance=request.user,data=request.POST)
        profile_form=ProfileEditForm(instance=request.user.profile,
        data=request.POST,
        files=request.FILES)
        if	user_form.is_valid()	and	profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,	'Profile	updated	'\
	               'successfully')
        else:
	        messages.error(request,	'Error	updating	your	profile')


    else:
        user_form	=	UserEditForm(instance=request.user)
        profile_form	=	ProfileEditForm(
        instance=request.user.profile)
    return	render(request,
	'account/edit.html',
	{'user_form':	user_form,
	'profile_form':	profile_form})

def user_login(request):
    if request.method =='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            user=authenticate(request,username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled Account')
            else:
                return HttpResponse('Invalid Login')
    else:
        form=LoginForm()
    return render(request,'account/login.html',{'form':form})

kabaadiwala/account/templates/base.html
{%	load	static	%}
<!DOCTYPE html>
   <html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Kabaadiwala.com</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
      <!-- style css -->
      <link rel="stylesheet" href="{%static 'css/style.css'%}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{%static 'css/responsive.css'%}">
      <!-- fevicon -->
      <link rel="icon" href="images/fevicon.png" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{%static 'css/jquery.mCustomScrollbar.min.css'%}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <!-- owl stylesheets --> 
      <link rel="stylesheet" href="{%static 'css/owl.carousel.min.css'%}">
      <link rel="stylesheet" href="{%static 'css/owl.theme.default.min.css'%}">
      
    
   </head>
   <!-- body -->
   <body class="main-layout">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="https://ik.imagekit.io/0xdm01uqieh/loading_X9pJkzrW_.gif?tr=w-1104,h-736,fo-auto" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
 

      <header class="section">
         <!-- header inner -->
        <div class="header_main">
         <div class="header_main">
            <div class="container">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo"> <a href="{% url 'home:index' %}"><img src="https://ik.imagekit.io/0xdm01uqieh/20210417_204800_0000-removebg-preview_7j7DyjQm_.png" alt="#"></a> </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <div class="menu-area">
                        <div class="limit-box">
                           <nav class="main-menu">
                              <ul class="menu-area-main">
                                 <li> <a href="{% url 'home:index' %}">Home</a> </li>
                                
								            <li><a href=" {% url 'addkabaad:list' %}">Buy</a></li>
                                    <li><a href="{% url 'addkabaad:create-sell' %}">Sell</a></li>
                                    <li><a href="{% url 'addkabaad:create-donate' %}">Donate</a></li>
                                
                                
                                 {%	if	request.user.is_authenticated	%}
                                 <li><a href="{% url 'logout' %}">Logout</a></li>
                                 {%	else	%}
                                 
                         <li><a href="{% url 'login' %}">Login</a></li>
                         {%	endif	%}
                              </ul>
                           </nav>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
        </div>
         <!-- end header inner -->
      </header>

	<div	id="content mb-5">
      
   {%	block	content	%}
      
     
	{%	endblock	%}
		</div>
	
	      <!-- end Contact Us-->
      <!-- footer start-->
      <div id="plant" class="footer layout_padding">
		<div class="container">
		   <p>© 2021 All Rights Reserved. </p>
		</div>
	 </div>

	 <!-- Javascript files-->
	 <script src="{%static 'js/jquery.min.js'%}"></script>
	 <script src="{%static 'js/popper.min.js'%}"></script>
	 <script src="{%static 'js/bootstrap.bundle.min.js'%}"></script>
	 <script src="{%static 'js/jquery-3.0.0.min.js'%}"></script>
	 <script src="{%static 'js/plugin.js'%}"></script>
	 <!-- sidebar -->
	 <script src="{%static 'js/jquery.mCustomScrollbar.concat.min.js'%}"></script>
	 <script src="{%static 'js/custom.js'%}"></script>
	 <!-- javascript --> 
	 <script src="{%static 'js/owl.carousel.js'%}"></script>
	 <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
	 <script>
		$(document).ready(function(){
		$(".fancybox").fancybox({
		openEffect: "none",
		closeEffect: "none"
		});
		
		$(".zoom").hover(function(){
		
		$(this).addClass('transition');
		}, function(){
		
		$(this).removeClass('transition');
		});
		});
		
	 </script> 
  </body>
</html>